[package]
name = "faultscope-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "faultscope"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
faultscope-artifact-elf = { path = "../faultscope-artifact-elf" }
faultscope-core = { path = "../faultscope-core" }
faultscope-model = { path = "../faultscope-model" }
serde_json.workspace = true
