[package]
name = "faultscope-registry"
edition.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
faultscope-arch-cortex-m = { path = "../faultscope-arch-cortex-m" }
faultscope-artifact-elf = { path = "../faultscope-artifact-elf" }
faultscope-core = { path = "../faultscope-core" }
faultscope-env-baremetal = { path = "../faultscope-env-baremetal" }
faultscope-env-freertos = { path = "../faultscope-env-freertos" }
faultscope-model = { path = "../faultscope-model" }

[dev-dependencies]
object = { workspace = true, features = ["write"] }
serde_json.workspace = true
