[package]
name = "faultscope-artifact-elf"
edition.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
addr2line.workspace = true
faultscope-core = { path = "../faultscope-core" }
faultscope-model = { path = "../faultscope-model" }
gimli = { workspace = true, features = ["endian-reader"] }
object.workspace = true

[dev-dependencies]
gimli = { workspace = true, features = ["write"] }
object = { workspace = true, features = ["write"] }
